$ErrorActionPreference='Stop'
if($PSVersionTable.PSEdition-eq'Core'){$ps5=Join-Path $env:WINDIR 'System32\WindowsPowerShell\v1.0\powershell.exe';&$ps5 -NoProfile -ExecutionPolicy Bypass -STA -File $PSCommandPath;if($LASTEXITCODE-ne0){throw ('Windows PowerShell test failed: '+$LASTEXITCODE)};return}
$root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;&(Join-Path $root 'app-studio.ps1') -CompileOnly
$temp=Join-Path ([IO.Path]::GetTempPath()) ('pui-report-'+[Guid]::NewGuid().ToString('N'));New-Item -ItemType Directory $temp|Out-Null
try{
 $imagePath=Join-Path $temp 'evidence.png';$bitmap=New-Object Drawing.Bitmap(20,12);try{$g=[Drawing.Graphics]::FromImage($bitmap);try{$g.Clear([Drawing.Color]::CornflowerBlue)}finally{$g.Dispose()};$bitmap.Save($imagePath,[Drawing.Imaging.ImageFormat]::Png)}finally{$bitmap.Dispose()}
 $recorder=New-Object AppStudio.SessionRecorder((Join-Path $temp 'shots'));$recorder.Data.Label='Report fixture';$record=New-Object AppStudio.ElementRecord;$record.ElementId='el-0001';$record.PinnedAt=[DateTimeOffset]::Now;$record.Label='Customer code';$record.Notes.Add('Check this field before automation.')
 $record.Uia=New-Object AppStudio.UiaInfo;$record.Uia.Status=[AppStudio.ProbeStatus]::Ok();$record.Uia.Name='Customer code';$record.Uia.AutomationId='CustomerCode';$record.Uia.ControlType='Edit';$record.Uia.FrameworkId='WinForm';$record.Uia.TreePath=@();$record.Uia.Children=@();$record.RecordedValue=New-Object AppStudio.RecordedValue;$record.RecordedValue.Length=24;$record.RecordedValue.Kind='string';$record.RecordedValue.Masked=$true;$record.RecordedValue.MaskRule='policy.maskedOnly'
 $record.Win32=New-Object AppStudio.Win32Info;$record.Win32.Status=[AppStudio.ProbeStatus]::Ok();$record.Win32.ProcessId=1234;$record.Win32.ClassName='Edit';$record.Win32.CtrlId=1002
 $shot=New-Object AppStudio.ShotResult;$shot.ShotId='sh-0001-crop';$shot.Kind='crop';$shot.File=$imagePath;$shot.CaptureMethod='BitBlt';$shot.Status=[AppStudio.ProbeStatus]::Ok();$shot.MaskedRects=@();$record.Shots.Add($shot);$recorder.Data.Shots.Add($shot)
 $snapshot=New-Object AppStudio.Snapshot;$snapshot.Uia=$record.Uia;$snapshot.Win32=$record.Win32;$target=New-Object AppStudio.TargetInfo;$target.TopLevelClass='Form';$locator=@([AppStudio.LocatorBuilder]::Build($snapshot,$target)|Where-Object{$_.Strategy-eq'uia.automationId'})[0];$ctx=New-Object AppStudio.ResolveContext;$ctx.Context='restart';$ctx.TargetRunId='run-02';$ctx.Original=$snapshot;$ctx.Candidates=@($snapshot);$null=[AppStudio.Resolver]::Resolve($locator,$ctx);$record.Locators.Add($locator)
 $probe=New-Object AppStudio.ProbeResult;$probe.ProbeId='pr-0001';$probe.Kind=[AppStudio.ProbeKind]::Invoke;$probe.RequestedAt=[DateTimeOffset]::Now;$probe.Method='uia.InvokePattern.Invoke';$probe.Outcome='unknown';$probe.DurationMs=181;$record.Probes.Add($probe);$recorder.Data.Elements.Add($record);$recorder.AddEvent('probe.run','tool','pr-0001 invoke unknown');$recorder.AddFailure('uia','UIA-TIMEOUT','Injected report diagnostic.','el-0001')
 $html=[AppStudio.Report]::Build($recorder.Data);$path=Join-Path $temp 'report.html';[IO.File]::WriteAllText($path,$html,(New-Object Text.UTF8Encoding($false)))
 foreach($section in @('id="conclusion"','id="index"','id="el-0001"','id="timeline"','id="diagnostics"','id="appendix"')){if(-not$html.Contains($section)){throw ('report section missing: '+$section)}}
 if($html-notmatch 'data:image/png;base64,[A-Za-z0-9+/=]+'){throw 'image was not embedded'};if($html-match '(?i)https?:|src="//|href="//|@import|fetch\s*\(|<iframe|<script|<link'){throw 'external reference or executable content found'};if($html-match '(?i)<input|<textarea|<button|<form|contenteditable|<select'){throw 'editing element found'}
 foreach($expected in @('CustomerCode','uia.automationId','same=','uia.InvokePattern.Invoke','unknown','UIA-TIMEOUT','Check this field','Full-screen captures cannot be masked automatically','schemaVersion: 1','MANIFEST.json')){if(-not$html.Contains($expected)){throw ('report content missing: '+$expected)}}
 $full=New-Object AppStudio.SessionRecorder((Join-Path $temp 'fullshots'));$full.SetValueCapture('full','explicit report test');$fullHtml=[AppStudio.Report]::Build($full.Data);if($fullHtml-notmatch 'recorded full value text by explicit selection'){throw 'full session conclusion warning missing'}
 Write-Output ('PASS test-report sections=6 image=data-uri externalRefs=0 editingElements=0 locator+verification+probe+timeline+diagnostics+environment=present fullBanner=present bytes='+([Text.Encoding]::UTF8.GetByteCount($html)))
}finally{Remove-Item $temp -Recurse -Force}
