$ErrorActionPreference='Stop'
if($PSVersionTable.PSEdition-eq'Core'){$ps5=Join-Path $env:WINDIR 'System32\WindowsPowerShell\v1.0\powershell.exe';&$ps5 -NoProfile -ExecutionPolicy Bypass -STA -File $PSCommandPath;if($LASTEXITCODE-ne0){throw ('Windows PowerShell test failed: '+$LASTEXITCODE)};return}
$root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;&(Join-Path $root 'app-studio.ps1') -CompileOnly
$temp=Join-Path ([IO.Path]::GetTempPath()) ('pui-isolation-'+[Guid]::NewGuid().ToString('N'));New-Item -ItemType Directory $temp|Out-Null
try{
 $secret1='isolation-secret-one-7f2a';$secret2='isolation-secret-two-9b4c';[Windows.Clipboard]::SetText('clipboard-sentinel')
 $snapshot=New-Object AppStudio.Snapshot;$snapshot.Uia=New-Object AppStudio.UiaInfo;$snapshot.Uia.Name='Customer';$snapshot.Uia.ControlType='Edit';$snapshot.Uia.LiveValue=$secret1;$snapshot.Uia.Status=[AppStudio.ProbeStatus]::Ok()
 $noRules=New-Object 'System.Collections.Generic.List[AppStudio.MaskRule]';$presenter=New-Object AppStudio.LiveValuePresenter;$first=$presenter.Present($snapshot,$noRules);if(-not$first.Visible-or$first.Text-ne$secret1-or$first.Notice-ne'Display only - not recorded'){throw 'live display contract mismatch'};$snapshot.Uia.LiveValue=$secret2;$second=$presenter.Present($snapshot,$noRules);if($second.Text-ne$secret2-or$presenter.Current.Text-eq$secret1){throw 'previous hover value was retained'};$presenter.Clear();if($null-ne$presenter.Current){throw 'stop did not clear live value'}
 $snapshot.Uia.IsPassword=$true;$password=$presenter.Present($snapshot,$noRules);if($password.Visible-or$password.Text){throw 'password value was displayed'};$snapshot.Uia.IsPassword=$false;$rule=New-Object AppStudio.MaskRule;$rule.RuleId='customer-mask';$rule.Kind='nameRegex';$rule.Pattern='Customer';$rule.AppliesTo='all';$rules=New-Object 'System.Collections.Generic.List[AppStudio.MaskRule]';$rules.Add($rule);$masked=$presenter.Present($snapshot,$rules);if($masked.Visible-or$masked.Text){throw 'nameRegex value was displayed'}
 $recorder=New-Object AppStudio.SessionRecorder((Join-Path $temp 'runtime\shots'));$recorder.AddMaskRule($rule);$record=New-Object AppStudio.ElementRecord;$record.ElementId='el-0001';$record.PinnedAt=[DateTimeOffset]::Now;$record.Label='Customer';$record.Uia=$snapshot.Uia;$record.Uia.LiveValue=$null;$record.Uia.Status=[AppStudio.ProbeStatus]::Ok();$record.RecordedValue=$recorder.RecordValueFor($snapshot.Uia,$record.ElementId);$probe=New-Object AppStudio.ProbeResult;$probe.ProbeId='pr-0001';$probe.Kind=[AppStudio.ProbeKind]::Read;$probe.RequestedAt=[DateTimeOffset]::Now;$probe.Method='uia.properties';$probe.Outcome='success';$probe.Before=New-Object AppStudio.ProbeObservation;$probe.Before.Value=$secret2;$probe.After=New-Object AppStudio.ProbeObservation;$probe.After.Value=$secret2;$record.Probes.Add($probe);$recorder.Data.Elements.Add($record);$recorder.AddEvent('probe.read','tool','pr-0001 uia.properties success');$recorder.AddFailure('uia','UIA-FAIL','Injected diagnostic without value.','el-0001')
 $pack=[AppStudio.PackWriter]::Write($recorder.Data,(Join-Path $temp 'pack'));if($pack.Status.State-ne'ok'){throw $pack.Status.Reasons[0].Message};foreach($file in Get-ChildItem $pack.Folder -File -Recurse|Where-Object{$_.Extension-ne'.png'}){$text=Get-Content $file.FullName -Raw;if($text.Contains($secret1)-or$text.Contains($secret2)){throw ('value leaked to '+$file.Name)}};if([Windows.Clipboard]::GetText()-ne'clipboard-sentinel'){throw 'clipboard was modified'}
 $fullRecorder=New-Object AppStudio.SessionRecorder((Join-Path $temp 'fullshots'));$fullRecorder.SetValueCapture('full','explicit test');if(@($fullRecorder.Data.Events|Where-Object{$_.Type-eq'mode.change'}).Count-ne1){throw 'full mode change event missing'}
 if(-not(Test-Path (Join-Path $pack.Folder 'report.html'))){throw 'self-contained report was not generated'};Write-Output ('PASS test-live-value-isolation displayOnlyNotice=1 hoverReplace=1 stopClear=1 passwordHidden=1 nameRegexHidden=1 session+report+log+events+locator+clipboard leak=0 fullModeEvent=1')
}finally{[Windows.Clipboard]::Clear();Remove-Item $temp -Recurse -Force}
