$ErrorActionPreference='Stop'
if($PSVersionTable.PSEdition-eq'Core'){$ps5=Join-Path $env:WINDIR 'System32\WindowsPowerShell\v1.0\powershell.exe';&$ps5 -NoProfile -ExecutionPolicy Bypass -STA -File $PSCommandPath;if($LASTEXITCODE-ne0){throw ('Windows PowerShell test failed: '+$LASTEXITCODE)};return}
$root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;&(Join-Path $root 'app-studio.ps1') -CompileOnly
$temp=Join-Path ([IO.Path]::GetTempPath()) ('pui-manifest-'+[Guid]::NewGuid().ToString('N'));New-Item -ItemType Directory $temp|Out-Null
try{
 $recorder=New-Object AppStudio.SessionRecorder((Join-Path $temp 'runtime\shots'));$recorder.AddFailure('uia','UIA-FAIL','Injected manifest fixture failure.','el-0001')
 $shotPath=Join-Path $temp 'runtime\shots\sample.png';New-Item -ItemType Directory (Split-Path $shotPath) -Force|Out-Null;$bitmap=New-Object Drawing.Bitmap(16,16);try{$bitmap.Save($shotPath,[Drawing.Imaging.ImageFormat]::Png)}finally{$bitmap.Dispose()};$shot=New-Object AppStudio.ShotResult;$shot.File=$shotPath;$shot.Kind='crop';$shot.ShotId='sh-0001-crop';$shot.Rect=New-Object AppStudio.RectValue;$shot.Rect.Width=16;$shot.Rect.Height=16;$shot.MaskedRects=@();$shot.Status=[AppStudio.ProbeStatus]::Ok();$recorder.AddShot($shot,'crop')
 $requested=Join-Path $temp 'pack';$result=[AppStudio.PackWriter]::Write($recorder.Data,$requested);if($result.Status.State-ne'ok'){throw $result.Status.Reasons[0].Message};foreach($required in @('session.json','diagnostics.log','README.txt','MANIFEST.json','shots/sample.png')){if(-not(Test-Path (Join-Path $result.Folder $required))){throw ('pack file missing: '+$required)}}
 $manifest=Get-Content (Join-Path $result.Folder 'MANIFEST.json') -Raw|ConvertFrom-Json;foreach($entry in $manifest.files){$path=Join-Path $result.Folder ($entry.file-replace'/','\');$actual=Get-Item $path;if($actual.Length-ne[long]$entry.bytes){throw ('byte mismatch '+$entry.file)};$hash=(Get-FileHash $path -Algorithm SHA256).Hash;if($hash-ne$entry.sha256){throw ('hash mismatch '+$entry.file)}};$sessionHash=(Get-FileHash (Join-Path $result.Folder 'session.json') -Algorithm SHA256).Hash;if($sessionHash-ne$manifest.sessionSha256){throw 'sessionSha256 mismatch'}
 $again=[AppStudio.PackWriter]::Write($recorder.Data,$requested);if($again.Folder-eq$result.Folder-or$again.Folder-notmatch'_2$'){throw 're-export overwrote the first folder'}
 $fileTarget=Join-Path $temp 'not-a-folder';[IO.File]::WriteAllText($fileTarget,'x');$failed=[AppStudio.PackWriter]::Write($recorder.Data,$fileTarget);if($failed.Status.State-ne'unavailable'-or$failed.Status.Reasons[0].Code-ne'PACK-WRITE'-or$failed.Folder-ne[IO.Path]::GetFullPath($fileTarget)){throw 'write failure was not explicit at the selected path'};if(Test-Path ($fileTarget+'_2')){throw 'writer silently fell back to another path'}
 Write-Output ('PASS test-manifest entries='+$manifest.files.Count+' bytes=all sha256=all sessionHash=ok reexport=_2 writeFailure=PACK-WRITE noFallback=1')
}finally{Remove-Item $temp -Recurse -Force}
