$ErrorActionPreference='Stop'
if($PSVersionTable.PSEdition-eq'Core'){$ps5=Join-Path $env:WINDIR 'System32\WindowsPowerShell\v1.0\powershell.exe';&$ps5 -NoProfile -ExecutionPolicy Bypass -STA -File $PSCommandPath;if($LASTEXITCODE-ne0){throw ('Windows PowerShell test failed: '+$LASTEXITCODE)};return}
$root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;&(Join-Path $root 'app-studio.ps1') -CompileOnly;[AppStudio.DpiAwareness]::Enable();$build=&(Join-Path $PSScriptRoot 'build-fixtures.ps1')
$temp=Join-Path ([IO.Path]::GetTempPath()) ('pui-canvas-'+[Guid]::NewGuid().ToString('N'));New-Item -ItemType Directory $temp|Out-Null;$process=$null
try{
 [AppStudio.Probe]::Configure($root,$false);$ready=Join-Path $temp 'ready.json';$process=Start-Process $build.FixtureCanvas -ArgumentList @('--ready',$ready) -PassThru;$limit=[DateTime]::UtcNow.AddSeconds(10);while(-not(Test-Path $ready)-and[DateTime]::UtcNow-lt$limit){Start-Sleep -Milliseconds 25};if(-not(Test-Path $ready)){throw 'FixtureCanvas not ready'};Start-Sleep -Milliseconds 300;$f=Get-Content $ready -Raw|ConvertFrom-Json
 if([AppStudio.WindowTools]::CountChildren([IntPtr][int64]$f.hwnd)-ne0){throw 'FixtureCanvas created a child HWND'};$physical=[AppStudio.WindowTools]::GetPhysicalRect([IntPtr][int64]$f.hwnd);$reference=New-Object AppStudio.ElementRef;$reference.X=$physical.X+[int]($physical.Width/2);$reference.Y=$physical.Y+[int]($physical.Height/2);$reference.Hwnd=[int64]$f.hwnd;$snapshot=[AppStudio.Probe]::Deep($reference,3000);if($snapshot.Win32.ClassName-ne'FixtureCanvasWindow'){throw ('canvas Win32 class mismatch: '+$snapshot.Win32.ClassName)}
 $empty=@($snapshot.UiaStatus.Reasons|Where-Object{$_.Code-eq'UIA-EMPTYTREE'});if($empty.Count-ne1-or$snapshot.UiaStatus.State-ne'partial'){throw ('UIA-EMPTYTREE missing: state='+$snapshot.UiaStatus.State+' type='+$snapshot.Uia.ControlType+' children='+$snapshot.Uia.Children.Count)}
 $target=New-Object AppStudio.TargetInfo;$target.TargetRunId='run-canvas';$target.ProcessName='FixtureCanvas';$target.TopLevelClass='FixtureCanvasWindow';$target.ClientRect=[AppStudio.WindowTools]::GetPhysicalRect([IntPtr][int64]$f.hwnd);$locators=[AppStudio.LocatorBuilder]::Build($snapshot,$target);if($locators.Count-ne1-or$locators[0].Strategy-ne'screen.relative'-or$locators[0].Confidence.Level-ne'low'){throw ('canvas locator fallback mismatch: '+(($locators|ForEach-Object{$_.Strategy})-join','))}
 $session=New-Object AppStudio.SessionRecorder((Join-Path $temp 'runtime\shots'));$record=$session.Pin($snapshot,'Custom canvas','painted surface');if($record.Shots.Count-ne1-or-not(Test-Path $record.Shots[0].File)){throw 'canvas crop/pin failed'};$read=[AppStudio.ProbeRunner]::Run($reference,[AppStudio.ProbeKind]::Read,(New-Object AppStudio.ProbeArgs));if($read.Outcome-ne'success'-or[string]::IsNullOrWhiteSpace($read.Method)){throw 'canvas read probe failed'};$session.AddProbe($record,$read);$pack=[AppStudio.PackWriter]::Write($session.Data,(Join-Path $temp 'pack'));if($pack.Status.State-ne'ok'){throw $pack.Status.Reasons[0].Message};foreach($name in @('report.html','session.json','diagnostics.log','README.txt','MANIFEST.json')){if(-not(Test-Path (Join-Path $pack.Folder $name))){throw ('canvas pack file missing '+$name)}}
 Write-Output ('PASS test-live-canvas childHwnd=0 uia=partial:UIA-EMPTYTREE locator=screen.relative:low crop=1 probe=read:'+ $read.Outcome+' packFiles='+$pack.Files.Count+' flow=select>inspect>pin>probe>export')
}finally{[AppStudio.Probe]::Shutdown();if($null-ne$process-and-not$process.HasExited){$process.Kill();$process.WaitForExit()};Remove-Item $temp -Recurse -Force}
