$ErrorActionPreference='Stop'
if($PSVersionTable.PSEdition-eq'Core'){$ps5=Join-Path $env:WINDIR 'System32\WindowsPowerShell\v1.0\powershell.exe';&$ps5 -NoProfile -ExecutionPolicy Bypass -STA -File $PSCommandPath;if($LASTEXITCODE-ne0){throw ('Windows PowerShell test failed: '+$LASTEXITCODE)};return}
$root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;&(Join-Path $root 'app-studio.ps1') -CompileOnly;[AppStudio.DpiAwareness]::Enable();$build=&(Join-Path $PSScriptRoot 'build-fixtures.ps1')
$temp=Join-Path ([IO.Path]::GetTempPath()) ('pui-capture-'+[Guid]::NewGuid().ToString('N'));New-Item -ItemType Directory $temp|Out-Null;$process=$null
function Center($r){return @([int](($r.left+$r.right)/2),[int](($r.top+$r.bottom)/2))}
try{
 [AppStudio.Probe]::Configure($root,$false);$ready=Join-Path $temp 'ready.json';$process=Start-Process $build.FixtureWinForms -ArgumentList @('--ready',$ready) -PassThru;$limit=[DateTime]::UtcNow.AddSeconds(10);while(-not(Test-Path $ready)-and[DateTime]::UtcNow-lt$limit){Start-Sleep -Milliseconds 25};if(-not(Test-Path $ready)){throw 'FixtureWinForms not ready'};Start-Sleep -Milliseconds 300;$f=Get-Content $ready -Raw|ConvertFrom-Json
 $normalPhysical=[AppStudio.WindowTools]::GetPhysicalRect([IntPtr][int64]$f.normal);$normal=[AppStudio.Probe]::At(($normalPhysical.X+[int]($normalPhysical.Width/2)),($normalPhysical.Y+[int]($normalPhysical.Height/2)),1500);if($normal.Uia.AutomationId-ne'CustomerCode'){throw ('normal automationId='+$normal.Uia.AutomationId)}
 $session=New-Object AppStudio.SessionRecorder((Join-Path $temp 'shots'));$record=$session.Pin($normal,'Customer code','normal note');if($record.RecordedValue.Content){throw 'maskedOnly retained value content'};if(-not$record.RecordedValue.Masked-or$record.RecordedValue.MaskRule-ne'policy.maskedOnly'){throw 'maskedOnly metadata mismatch'};if($record.Shots.Count-ne1-or-not(Test-Path $record.Shots[0].File)){throw 'normal crop missing'}
 $passwordPhysical=[AppStudio.WindowTools]::GetPhysicalRect([IntPtr][int64]$f.password);$password=[AppStudio.Probe]::At(($passwordPhysical.X+[int]($passwordPhysical.Width/2)),($passwordPhysical.Y+[int]($passwordPhysical.Height/2)),1500);if(-not$password.Uia.IsPassword){throw 'IsPassword was false'};$passwordRecord=$session.Pin($password,'Password','password note');if($passwordRecord.RecordedValue.Content-or$passwordRecord.RecordedValue.MaskRule-ne'isPassword'){throw 'password value policy mismatch'};if($passwordRecord.Shots[0].MaskedRects.Count-ne1){throw 'password mask metadata missing'}
 $bitmap=New-Object Drawing.Bitmap($passwordRecord.Shots[0].File);try{$pixel=$bitmap.GetPixel([int]($bitmap.Width/2),[int]($bitmap.Height/2));if($pixel.R-ne0-or$pixel.G-ne0-or$pixel.B-ne0){throw 'password crop center was not black'}}finally{$bitmap.Dispose()}
 $blocked=[AppStudio.Capture]::Full((Join-Path $temp 'blocked.png'),$false);if($blocked.Status.State-ne'unavailable'-or(Test-Path (Join-Path $temp 'blocked.png'))){throw 'implicit full capture was not blocked'}
 $full=[AppStudio.Capture]::Full((Join-Path $temp 'full.png'),$true);if($full.Status.State-ne'ok'-or-not(Test-Path $full.File)-or[string]::IsNullOrWhiteSpace($full.Warning)){throw 'explicit full capture failed'}
 $preview=Join-Path $temp 'session-preview.json';$session.WritePreview($preview);$text=Get-Content $preview -Raw;if($text.Contains('secret-value-42')-or$text.Contains('P@ssword123')){throw 'value leaked to preview'}
 Write-Output ('PASS test-capture-policy normalCrop=1 passwordMask=black fullImplicit=blocked fullExplicit=ok valueLeak=0')
}finally{[AppStudio.Probe]::Shutdown();if($null-ne$process-and-not$process.HasExited){$process.Kill();$process.WaitForExit()};Remove-Item $temp -Recurse -Force}
